### ISSUE TITLE
URL to the paper seems to be broken

### ISSUE THREAD

**Issue by liviu-** [reedscot/nips2016#1]
Hey, thanks for sharing this project!

Just thought I should let you know that the URL linked in the header (http://umich.edu/~reedscot/nips2016.pdf) gives me this:
![2016-10-09-182713_713x366_scrot](https://cloud.githubusercontent.com/assets/9915183/19222361/64062a60-8e4e-11e6-93a7-2187dd526c95.png)

I ended up downloading it from [here](https://www.researchgate.net/publication/308335116_Learning_What_and_Where_to_Draw) instead.

**Comment by reedscot** [comment]
Thanks! Should be fixed now.
